import { test, expect } from '@playwright/test'

test('stacked shop Omens deliver Rare+, editions and free packs on a small screen', async ({
  page,
}, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/en/play')
  await expect(page.locator('[data-game-action="play"]')).toBeVisible()
  const fixture = await page.evaluate(async () => {
    const gamePath = '/src/game/GameOrchestrator.ts'
    const storePath = '/src/stores/omenStore.ts'
    const definitionPath = '/src/config/omenDefinitions.ts'
    const eventPath = '/src/game/EventBus.ts'
    const { gameOrchestrator: game } = await import(gamePath)
    const { useOmenStore } = await import(storePath)
    const definitions = await import(definitionPath)
    const { eventBus } = await import(eventPath)
    game.startNewRun(9)
    Object.assign(game.getState(), {
      phase: 'shop',
      lastCompletedRoundType: 'Small',
      gold: 100,
    })
    // Deliberate accumulated-Omens fixture. Offers are generated by the real session.
    for (const key of [
      'DECREE_OMEN',
      'SEAL_OMEN',
      'OMEN_OF_CRESCENTS',
      'VOID_OMEN',
      'BLESSING_PACK_OMEN',
      'BLESSING_PACK_OMEN',
      'BLESSING_PACK_OMEN',
      'FOIL_OMEN',
      'HOLOGRAPHIC_OMEN',
      'NEGATIVE_OMEN',
    ]) {
      if (!useOmenStore.getState().addOmen(definitions[key]))
        throw new Error(`Missing Omen ${key}`)
    }
    game.shop.open()
    eventBus.emit('shopUpdated', { isOpen: true })
    const items = game.shop.state.itemOfferings
    const rare = items[0]
    return {
      ids: items.map((item: { id: string }) => item.id),
      types: items.map((item: { itemType: string }) => item.itemType),
      rare: {
        id: rare.id,
        decreeId: rare.item.id,
        name: rare.item.name,
        rarity: rare.item.rarity,
        edition: rare.item.edition,
        cost: rare.finalCost,
      },
      packs: game.shop.state.packOfferings.map(
        (item: { id: string; item: { id: string }; finalCost: number }) => ({
          id: item.item.id,
          cost: item.finalCost,
        })
      ),
    }
  })
  await expect(page).toHaveURL(/\/en\/shop$/)
  expect(fixture.types).toEqual([
    'Decree',
    'FateSeal',
    'CelestialOrb',
    'VoidScript',
    'Decree',
    'Decree',
  ])
  expect(fixture.rare).toMatchObject({
    rarity: 'ImperialDecree',
    edition: 'Foil',
    cost: 0,
  })
  expect(fixture.packs).toHaveLength(3)
  expect(fixture.packs.every((pack: { cost: number }) => pack.cost === 0)).toBe(
    true
  )
  await expect(page.locator('[data-shop-item]')).toHaveCount(6)
  for (const id of fixture.ids) {
    const card = page.locator(`[data-shop-item="${id}"]`)
    await card.scrollIntoViewIfNeeded()
    await expect(card.getByRole('heading')).toBeVisible()
    expect(
      await card.evaluate((node) =>
        Array.from(node.querySelectorAll<HTMLElement>('h3,p')).every(
          (child) =>
            child.scrollHeight <= child.clientHeight + 1 &&
            child.scrollWidth <= child.clientWidth + 1
        )
      )
    ).toBe(true)
  }
  const rareCard = page.locator(`[data-shop-item="${fixture.rare.id}"]`)
  await rareCard.scrollIntoViewIfNeeded()
  await page.screenshot({
    path: testInfo.outputPath('omen-rare-offer-320.png'),
  })
  await rareCard.getByRole('button').click()
  await expect(rareCard).toHaveCount(0)
  const pack = page.locator(`[data-shop-pack="${fixture.packs[0].id}"]`)
  await pack.scrollIntoViewIfNeeded()
  await pack.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await dialog
    .getByRole('button', { name: 'Skip rewards', exact: true })
    .click()
  await expect(dialog).not.toBeVisible()
  const state = await page.evaluate(async (decreeId) => {
    const gamePath = '/src/game/GameOrchestrator.ts'
    const storePath = '/src/stores/omenStore.ts'
    const { gameOrchestrator: game } = await import(gamePath)
    const { useOmenStore } = await import(storePath)
    const owned = game
      .getState()
      .decreeSystem.getOwnedDecrees()
      .filter((d: { id: string }) => d.id === decreeId)
    return {
      gold: game.getState().gold,
      editions: owned.map((d: { edition: string }) => d.edition),
      pending: game.shop.pendingPack !== null,
      visits: game.shop.visitTotals,
      active: useOmenStore.getState().activeTags.length,
      consumed: useOmenStore.getState().consumedTags.length,
    }
  }, fixture.rare.decreeId)
  expect(state).toEqual({
    gold: 95,
    editions: ['Foil'],
    pending: false,
    visits: { goldSpent: 0, itemsPurchased: 2 },
    active: 0,
    consumed: 10,
  })
  await page.getByRole('button', { name: 'Reroll', exact: true }).click()
  await expect(page.locator('[data-shop-item]')).toHaveCount(1)
  // Revisit through the client router: a document reload intentionally starts
  // a new Classic session and is not a same-visit persistence guarantee.
  await page.evaluate(() => {
    history.pushState({}, '', '/en/settings')
    dispatchEvent(new PopStateEvent('popstate'))
  })
  await expect(page).toHaveURL(/\/en\/settings$/)
  await page.goBack()
  await expect(page).toHaveURL(/\/en\/shop$/)
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  expect(
    await page.evaluate(async () => {
      const path = '/src/game/GameOrchestrator.ts'
      const { gameOrchestrator: game } = await import(path)
      return {
        gold: game.getState().gold,
        items: game.shop.state.itemOfferings.length,
      }
    })
  ).toEqual({ gold: 90, items: 2 })
  expect(
    await page.evaluate(
      () => document.documentElement.scrollWidth <= innerWidth
    )
  ).toBe(true)
})
